project:
  type: website
  output-dir: docs

website:
  title: "Maternal Health"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JiaQuanLim/maternal_health_blog

format:
  html:
    theme: cosmo
    css: styles.css



